[cursor]
image = false # use an image for the cursor
image_path = "" # set to local path of image if using an image for the cursor
color = [255,181,192,255] # rgba, modulates color of image if using one
size = 24.0

[background]
color = [0, 255, 0, 255] # rgba, set to green screen by default
screen_size = [1920, 1080] # width x height

[trail]
enabled = true
fade = true # does the cursor trail fade out
time = 0.2 # how long in the trail lasts until fully invisible in seconds
color = [177, 156, 215, 255] # rgba
size = 18.0
image = false # use an image for the trail
image_path = "" # set to local path of image if using an image for the trail